[theme]
base = "light"
primaryColor = "#a24b2d"
backgroundColor = "#f4f0e6"
secondaryBackgroundColor = "#fffdf8"
textColor = "#1c1915"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
